runtime: python310
instance_class: F4_1G #https://cloud.google.com/appengine/docs/standard
env_variables:
  APP_SETTINGS: config.Config
  SECRET_KEY: ljdfl12317269hjgjhfjhgwuydeg17236812631uehwigejbjewkeqjjkhekjhqkjwe123123
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:Aasfe2mkrjewnkfwn234j232id2k@35.224.57.119:5432/postgres
  DB_ENGINE: postgresql
  DB_NAME: postgres
  DB_USERNAME: postgres
  DB_PASS: Aasfe2mkrjewnkfwn234j232id2k
  DB_HOST: "35.224.57.119"
  DB_PORT: 5432
  DEBUG: False
  FLASK_DEBUG: False

